### ISSUE TITLE
Guide should be updated to specify Python version requirement.

### ISSUE THREAD

**Issue by TunaCici** [GustavoJST/CLID#1]
I was following the guide to install CLID. But there were some errors because I was using Python 2.7 on Ubuntu 18.04. I tried Python 3.9 but that too didn't work. Apparently there are some operations like ' | ' which only available on Python 3.10+. I think this information should be added to the guide for others like me. 

Thanks for your work btw. It works great.

**TLDR;** A requirement should be added to the docs/guide.md to specify **Python 3.10+ is required**.

**Comment by GustavoJST** [comment]
You're right. Indeed, CLID only works on Python 3.10+. I'll update the README and guide files. Thanks for letting me know and sorry for any inconvenience.
